### ISSUE TITLE
Can 63 Corvi DLC run on Mac?

### ISSUE THREAD

**Issue by mikezang** [spacechem-community-developers/SpaceChem-Community-Edition#18]
There is no Mac in information about 63 Corvi DLC, is it no problems to played on Mac?

**Comment by csaboka** [comment]
The DLC is supported on Mac. If you run into issues, you can always contact Zachtronics directly by sending an e-mail to zach@zachtronics.com .

I'm closing this since it doesn't have to do anything with the Community Edition. You can contact Zachtronics directly with questions about the original game, or you can ask your questions from the community. (I've pointed out the places you can ask your questions in my comment on #17 )
