### ISSUE TITLE
Make holding backspace on a rename solution repeatedly backspace

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#29]
This has already been recommended in The Discord.  Sorry for the duplicate if that is undesired.

When renaming a solution, please make holding backspace repeatedly backspace like that does in normal applications.  Don't make me keep hitting the backspace button to delete a solution name.

**Comment by csaboka** [comment]
As I said on Discord, the tricky part is getting your OS preference for key repetition. I could hardcode a repetition rate, but it wouldn't be very elegant, and making it configurable specifically for this game would be weird.

In other words, this is not impossible, just pretty annoying to implement, especially because the rate querying would have to be written three times (for Windows, Linux and Mac).

**Comment by csaboka** [comment]
With yesterday's changes on the main code base, this is now a relatively simple fix. It's annoying me, too, so I'll try to fix it today.

**Comment by csaboka** [comment]
The next CE release should have this functionality

**Comment by csaboka** [comment]
The updated CE has been pushed to Steam. Backspace should work as expected now. Feel free to reopen if you notice anything out of the ordinary with this functionality.
