### ISSUE TITLE
Add a "check for updates" feature to CE

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#34]
If you're not active in The Discord, you typically don't know when there's an update to the CE.  Is it possible to add a button that checks for updates and automatically applies them if there are?

Or hell, if you can do that, just check the server when the game starts up and, if there is one, ask the user if they want to take it.

**Comment by csaboka** [comment]
Looks like GitHub has a friendly interface that would allow finding the latest release relatively straightforward. Self-updating executables are tricky to implement (especially on Windows, where a running executable cannot be deleted).

Honestly, I will treat this as low priority. I'm sure there are more useful things the community would like to see. If it does get implemented, it will be just a prompt that lets you visit GitHub to download it for yourself, since that solves the most important part without having to deal with complicated things.

Please note that beyond Discord, we also announce new versions on Reddit and in a Steam discussion topic. If you subscribe to the latter, Steam will notify you about new posts.

**Comment by csaboka** [comment]
The next version after the tournament finishes will have a message like this:
![image](https://user-images.githubusercontent.com/2852084/85947936-fe66ed00-b94d-11ea-9f51-d66fae91a596.png)
Update checks will happen no more than once a day and can be disabled. If you don't have an Internet connection during a check, or any other issue prevents the game from reaching the GitHub servers, it will just silently give up and try again tomorrow.

**Comment by 12345ieee** [comment]
With 1st party Steam support starting in v6.0, this is no longer needed.
