### ISSUE TITLE
Add an option to switch glyphs of the same type when dragging one over the other

### ISSUE THREAD

**Issue by Darayavaush** [spacechem-community-developers/SpaceChem-Community-Edition#42]

**Comment by csaboka** [comment]
This will be part of the next CE release.

The actual feature is a bit more lenient than what was requested because it allows swapping any two features that have the same size (i.e. splitters and fusers can be swapped with each other, and any single-tile feature can be swapped with any other). The overlap must be exact, though, i.e. it won't allow you to drop a splitter into a position that overlaps just half of another splitter.
