### ISSUE TITLE
Allow viewing the scores of more than 11 steam friends at a time

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#45]

**Comment by csaboka** [comment]
The tricky thing here is designing the UI, not the actual coding itself. You can see the leaderboards in two places:
* During level selection
* After completing a level

The first one is available at any time, so that's where people would use this the most. Unfortunately, it's also the one where the UI options are limited. You need to hover over some other UI element (the representation of the level itself) to show the leaderboards, so you can't click on the leaderboards to either switch them to a larger view or to scroll them.

The best I can think of is allowing the wheel to scroll the leaderboards, but that would be almost impossible to discover on your own, which is usually a bad sign in UI design.

**Comment by csaboka** [comment]
This will be part of the next CE release.

I couldn't come up with a very good UI for this, so I ended up just with Shift+Mousewheel on level select screens and just regular mousewheel on the completion screen. (Regular wheel is used on the ResNet journal screen to scroll between pages, that's why this had to be assigned to Shift+Mousewheel.) To make this a bit more discoverable, I've also extended the help message next to the leaderboard so it also tells you about using the wheel, in addition to telling you about Tab.

I'm still open to any improvement ideas on the UI.
