### ISSUE TITLE
Solution browser trims the solution metric when it's above 10 symbols

### ISSUE THREAD

**Issue by Darayavaush** [spacechem-community-developers/SpaceChem-Community-Edition#51]
Basically, 11111/1/111 gets rendered as "11111/1/1..", which is hella inconvenient.

**Comment by csaboka** [comment]
This should be fixed in the next release.

We're working with limited space here (the graphics fall apart if the dialog box gets too wide), but I've rearranged things to make the score fit by making the buttons narrower. It's also using shortening logic above 5 digits now, so 11111 will show as is, but 111111 will show up as "111k", 1111111 as "1.11M", 11111111 as "11.1M" and 111111111 as "111M". Numbers above one billion will just show up as "+INF".
