### ISSUE TITLE
Request: Option to reduce or get rid of the effect when adding / removing a bond

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#59]
When adding / removing a bond, the game puts big "+" or "-" or "Max Bonds" images over the bonders.  It's often impossible to see the actual bonds in the molecules.  Please add an option to reduce these effects.  If that's too hard, you may want to eliminate or change that effect entirely, but that could have it's own visual drawbacks.

**Comment by csaboka** [comment]
This will be part of the next CE release.

When the option is on, Bond+ and Bond- effects will work like MAX BONDS effects, i.e. there will be only one of them and they will fly straight up instead of in a random direction. This should hopefully make it easier to see what exactly happened in response of a bond command, but things can still overlap in a confusing way when bond commands are executed in quick succession.
