### ISSUE TITLE
Regular bonders vs bonder-plus/bonder-minus priorities

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#69]
When a custom research level (/reactor) is created that contains both regular bonders and plus and/or minus-only bonders, a default newly-created solution has all regular bonders prioritized before all bonders of the other types (as revealed by having bonder priority on). However, re-ordering the relevant lines in the solution file can make a valid solution which prioritizes e.g. plus-bonders before regular bonders, which is impossible to achieve within the game proper.

Assuming this inconsistency is undesirable, the simplest fix is probably to ensure all restricted bonders appear after all regular bonders in the solution file. Allowing their priorities to be switched in-game would be difficult. The inability to prioritize plus-bonders higher will only matter in a few edge case solutions.

**Comment by csaboka** [comment]
The export file is a red herring here. Anything you can do by editing the export file can also be done by editing your save file directly, exporting and importing just makes it easier. So this kind of check would have to be done every time a level is loaded, not just when a solution is being imported.

That said, I'd prefer this kind of reordering to be possible instead of being banned, but you're correct that implementing it in the game itself isn't that easy. I'm not sure what's the best way to proceed here.

**Comment by csaboka** [comment]
I think I've found a minimally ugly way to allow changing bonder priorities in-game. I'll update this issue once I'm sure my approach will actually work.

**Comment by csaboka** [comment]
My approach looks promising, but it will need some further testing. The idea is that you can adjust the priority of a bonder up or down using the mouse wheel, and the game will make the necessary DB changes. (Increasing and decreasing the priority is implemented by swapping the bonder with the one after/before it in the priority order.)

**Comment by csaboka** [comment]
This will be part of the next release.

**Comment by 12345ieee** [comment]
See https://github.com/spacechem-community-developers/SpaceChem-Community-Edition#allow-direct-adjustment-of-feature-priorities
